function aliceMovies(Gavg,prefix)
wts='general,3-35Hz,alla.wts';
sf={'idan'  'inbal'  'liron'  'maor'  'odelia'	'ohad'  'yoni' 'mark'};
Xlim=[0.05 0.25];
cd /home/yuval/Copy/MEGdata/alice/ga2015
load GavgEqTrl
conds={'avgMr','GavgM20'};
%!echo "cd /home/yuval/Copy/MEGdata/alice" > ~/alice2tlrc
prefix={'Ma','Mw'};
scale=1e-13;
for subi=1:8
    cd(['/home/yuval/Copy/MEGdata/alice/',sf{subi}])
    %load ('SAM/general,3-35Hz,alla.wts')
    cd SAM
    [~, ~, ActWgts]=readWeights(wts);
    cd ..
    %load SAM/noiseNormCov
    ns=mean(abs(ActWgts),2);
    cd MRI
    for condi=1:2
        Gavg=eval(conds{condi});
        samples=[nearest(Gavg.time,Xlim(1)),nearest(Gavg.time,Xlim(2))];
        data=squeeze(Gavg.individual(subi,:,samples(1):samples(2)));
        vs=ActWgts*data;
%         if condi==1
%             samplesBL=[nearest(Gavg.time,-0.2),nearest(Gavg.time,-0.05)];
%             BL=squeeze(Gavg.individual(subi,:,samplesBL(1):samplesBL(2)));
%             vsBL=ActWgts*BL;
%             scale=meanWnan(mean(abs(vsBL'))./mean(abs(ActWgts')));
%         end
        
        vs=vs./repmat(ns,1,size(vs,2))./scale;
        vs=abs(vs);
        vs(isnan(vs))=0;
        %make 3D image
        
        
        cfg=[];
        cfg.step=5;
        cfg.boxSize=[-120 120 -90 90 -20 150];
        cfg.prefix=prefix{condi};
        cfg.torig=50;
        cfg.TR=1/1.0172;
        VS2Brik(cfg,vs);
        %eval(['!echo "cd ',pwd,'" >> ~/alice2tlrc'])
        eval(['!@auto_tlrc -apar ortho+tlrc -input ',prefix{condi},'+orig -dxyz 5'])
        %!mv ',prefix,'+tlrc.HEAD /home/yuval/Copy/MEGdata/alice/func/',prefix,'_',num2str(subi),'+tlrc.HEAD" >> ~/alice2tlrc']);
        eval(['!mv ',prefix{condi},'+tlrc.BRIK /home/yuval/Copy/MEGdata/alice/ga2015/func/',prefix{condi},'_',num2str(subi),'+tlrc.BRIK']);
        eval(['!mv ',prefix{condi},'+tlrc.HEAD /home/yuval/Copy/MEGdata/alice/ga2015/func/',prefix{condi},'_',num2str(subi),'+tlrc.HEAD']);
    end
end
cd /home/yuval/Copy/MEGdata/alice/ga2015/func
!3dcalc -a Ma_1+tlrc -b Ma_2+tlrc -c Ma_3+tlrc -d Ma_4+tlrc -e Ma_5+tlrc -f Ma_6+tlrc -g Ma_7+tlrc -h Ma_8+tlrc -exp "(a+b+c+d+e+f+g+h)/8" -prefix GavgMa
masktlrc('GavgMa+tlrc','MASKctx');
!3dcalc -a Mw_1+tlrc -b Mw_2+tlrc -c Mw_3+tlrc -d Mw_4+tlrc -e Mw_5+tlrc -f Mw_6+tlrc -g Mw_7+tlrc -h Mw_8+tlrc -exp "(a+b+c+d+e+f+g+h)/8" -prefix GavgMw
masktlrc('GavgMw+tlrc','MASKctx+tlrc');
%3dttest++ 
command = ['~/abin/3dttest++ -paired -no1sam -mask ~/SAM_BIU/docs/MASKctx+tlrc -prefix M190',...
        ' -setA Sacc ',...
        ' sub1 Ma_1+tlrc[147]',...
        ' sub2 Ma_2+tlrc[147]',...
        ' sub3 Ma_3+tlrc[147]',...
        ' sub4 Ma_4+tlrc[147]',...
        ' sub5 Ma_5+tlrc[147]',...
        ' sub6 Ma_6+tlrc[147]',...
        ' sub7 Ma_7+tlrc[147]',...
        ' sub8 Ma_8+tlrc[147]',...
        ' -setB WbW ',...
        ' sub1 Mw_1+tlrc[147]',...
        ' sub2 Mw_2+tlrc[147]',...
        ' sub3 Mw_3+tlrc[147]',...
        ' sub4 Mw_4+tlrc[147]',...
        ' sub5 Mw_5+tlrc[147]',...
        ' sub6 Mw_6+tlrc[147]',...
        ' sub7 Mw_7+tlrc[147]',...
        ' sub8 Mw_8+tlrc[147]'];
    [~, ~] = unix(command);
command = ['~/abin/3dttest++ -paired -no1sam -mask ~/SAM_BIU/docs/MASKctx+tlrc -prefix M100',...
        ' -setA Sacc ',...
        ' sub1 Ma_1+tlrc[49]',...
        ' sub2 Ma_2+tlrc[49]',...
        ' sub3 Ma_3+tlrc[49]',...
        ' sub4 Ma_4+tlrc[49]',...
        ' sub5 Ma_5+tlrc[49]',...
        ' sub6 Ma_6+tlrc[49]',...
        ' sub7 Ma_7+tlrc[49]',...
        ' sub8 Ma_8+tlrc[49]',...
        ' -setB WbW ',...
        ' sub1 Mw_1+tlrc[49]',...
        ' sub2 Mw_2+tlrc[49]',...
        ' sub3 Mw_3+tlrc[49]',...
        ' sub4 Mw_4+tlrc[49]',...
        ' sub5 Mw_5+tlrc[49]',...
        ' sub6 Mw_6+tlrc[49]',...
        ' sub7 Mw_7+tlrc[49]',...
        ' sub8 Mw_8+tlrc[49]'];
    [~, ~] = unix(command);