function [figure1]=ambRMSfigureUR4
% cd /home/yuval/Dropbox/MEGpaper/files/matlab
% load /home/yuval/Documents/Dropbox/MEGpaper/files/matlab/smooth20RMS.mat
% load /home/yuval/Documents/Dropbox/MEGpaper/files/matlab/RMS_UR.mat
load /home/yuval/Dropbox/MEGpaper/files/matlab/RMS_2013_allConds1BL.mat
tmln1=-300.0177:0.9823:699;
areaVector(1,1:1018)=0;
areaVector(1,460:700)=20;
yl=[-2 10];
ylabels=[0 5 10];

rmsUR=[]; % 
m=squeeze(mean(LrmsBL(:,3,:),3));
rmsUR(1:1018,1)=smooth(m,20);
m=squeeze(mean(RrmsBL(:,3,:),3));
rmsUR(1:1018,2)=smooth(m,20);
m=squeeze(mean(LrmsBL(:,9,:),3));
rmsUR(1:1018,3)=smooth(m,20);
m=squeeze(mean(RrmsBL(:,9,:),3));
rmsUR(1:1018,4)=smooth(m,20);
rmsUR=rmsUR*10^14;
m=mean(mean(rmsUR(102:306,:))); % BL again, wasn't around zero
rmsUR=rmsUR-m;
rmsUR(1:1018,5)=0;
rmsUR([460 545 700],5)=20;


rms=[]; % 
m=squeeze(mean(LrmsBL(:,2,:),3));
rms(1:1018,1)=smooth(m,20);
m=squeeze(mean(RrmsBL(:,2,:),3));
rms(1:1018,2)=smooth(m,20);
m=squeeze(mean(LrmsBL(:,8,:),3));
rms(1:1018,3)=smooth(m,20);
m=squeeze(mean(RrmsBL(:,8,:),3));
rms(1:1018,4)=smooth(m,20);
rms=rms*10^14;
m=mean(mean(rms(102:306,:))); % BL again, wasn't around zero
rms=rms-m;
rms(1:1018,5)=0;
rms([460 545 700],5)=20;



%RMSfigure7(tmln1, s, areaVector)

%CREATEFIGURE(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 22-Jun-2010 10:21:34
%% black and white figure
% Create figure
fontSize=12;
figure1 = figure('XVisual',...
    '0x65 (TrueColor, depth 32, RGB mask 0xff0000 0xff00 0x00ff)');

% axes1 = axes('YTick',ylabels,'YTickLabel',ylabels/100,'XTick',[0 200 400 600],...
%     'FontSize',fontSize,'FontName','Times New Roman','FontWeight','bold');
pl1=subplot(1,2,2)
xlim([-200 700]);
ylim(yl);
set(pl1,'FontSize',fontSize,'FontName','Times New Roman','FontWeight','bold',...
    'YTick',ylabels,'YTickLabel',ylabels/100,'XTick',[0 200 400 600])
%box('on');
hold('all');
% Creating area
area(tmln1,areaVector,'LineStyle','none','FaceColor',[0.9059 0.9059 0.9059]);
% Create multiple lines using matrix input to plot
plot1=plot(tmln1,rmsUR,'Color',[0 0 0]);
set(plot1(1),'LineWidth',2);
set(plot1(2),'LineWidth',2,'LineStyle','--');
set(plot1(3),'LineWidth',1);
set(plot1(4),'LineWidth',1,'LineStyle','--');
set(plot1(5),'LineWidth',2);


% Create legend
legend([plot1(1:4)],'Dom L','Dom R','Sub L','Sub R','Location','NorthEast');
set(legend,'EdgeColor',[1 1 1],'FontWeight','bold','LineStyle','none','FontName','Times New Roman','FontSize',fontSize-2);
title('UNRELATED')


%%
pl2=subplot(1,2,1)
% axes2 = axes('Parent',figure2,'YTick',ylabels,'YTickLabel',ylabels/100,'XTick',[0 200 400 600],...
%     'FontSize',fontSize,'FontName','Times New Roman','FontWeight','bold');
xlim([-200 700]);
ylim(yl);
set(pl2,'FontSize',fontSize,'FontName','Times New Roman','FontWeight','bold',...
    'YTick',ylabels,'YTickLabel',ylabels/100,'XTick',[0 200 400 600])

%box('on');
hold('all');
% Creating area
area(tmln1,areaVector,'LineStyle','none','FaceColor',[0.9059 0.9059 0.9059]);
% Create multiple lines using matrix input to plot
plot2=plot(tmln1,rms,'Color',[0 0 0]);
set(plot2(1),'LineWidth',2);
set(plot2(2),'LineWidth',2,'LineStyle','--');
set(plot2(3),'LineWidth',1);
set(plot2(4),'LineWidth',1,'LineStyle','--');
set(plot2(5),'LineWidth',2);
% Create ylabel
ylabel('RMS (pT)','FontWeight','bold','FontSize',fontSize,'FontName','Times New Roman');
% Create legend
%legend1 = legend(axes1,'show');
%set(legend1,'Location','NorthWest','FontWeight','bold');
title('RELATED')
xlabel('Time(ms)')
