function kurFigWindows
load /home/yuval/Data/kurtosis/b024/vsLR
X1=lat;
YMatrix1=[sumG2L;sumG2R];
%CREATEFIGURE(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 09-Jan-2013 14:58:11

% Create figure
figure1 = figure('XVisual',...
    '0x29 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)',...
    'PaperSize',[20.98404194812 29.67743169791],...
    'InvertHardcopy','off',...
    'Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1,'XTick',[0.125 0.25 0.5 1 2 4 8 16 32],...
    'XScale','log',...
    'XMinorTick','on',...
    'LineWidth',2,...
    'FontSize',20,...
    'FontName','Times');
% Uncomment the following line to preserve the Y-limits of the axes
%ylim(axes1,[0 50]);
% Uncomment the following line to preserve the Z-limits of the axes
%zlim(axes1,[-1 1]);
hold(axes1,'all');

% Create multiple lines using matrix input to semilogx
semilogx1 = semilogx(X1,YMatrix1,'Parent',axes1,'LineWidth',2,...
    'LineStyle','none',...
    'Color',[0 0 0]);
set(semilogx1(1),'MarkerSize',30,'Marker','.','DisplayName','Large Spike');
set(semilogx1(2),'MarkerFaceColor',[0 0 0],'MarkerSize',10,'Marker','^',...
    'DisplayName','Frequent Spike');

% Create xlabel
xlabel('Time Window (Seconds)','FontSize',20,'FontName','Times');

% Create ylabel
ylabel('Maximum g2','FontSize',20,'FontName','Times');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.179303507596068 0.725048449612403 0.274100759606792 0.150436046511628],...
    'LineWidth',2);

