function figure1=KurFigA22vs
load /home/yuval/Data/kurtosis/b044/figA22vs.mat

%CREATEFIGURE(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 03-Jan-2013 17:55:00

% Create figure
figure1 = figure('XVisual',...
    '0x29 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)',...
    'Position',[1,1,1000,600]);

% Create axes
axes1 = axes('Parent',figure1,'YTickLabel',{'','','','',''},'FontSize',20,...
    'LineWidth',2,...
    'FontName','Times');
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot(timeline,Ymat,'Color',[0 0 0],'Parent',axes1,'LineWidth',2);

% Create xlabel
xlabel('Time (Sec)','FontSize',20,'FontName','Times');

% Create ylabel
ylabel('Normalized Amplitude','FontSize',20,'FontName','Times');

% Create title
title('A Sensor and Virtual Sensors after 20-70Hz band-pass filter',...
    'FontSize',20,...
    'FontName','Times');

% Create textbox
annotation(figure1,'textbox',...
    [0.17 0.25 0.45 0.575],...
    'String',{'MEG sensor A22','','','','','','Frontal Virtual Sensor, g2=2.15','','','Parietal Virtual Sensor, g2=0.55'},...
    'FontSize',20,...
    'FontName','Times',...
    'FitBoxToText','off',...
    'LineStyle','none');
box off

