freq=10;
stat=statPlot('talResults/Coh/cohLRv1post_D','talResults/Coh/cohLRv1pre_D',[freq freq],[0 1],'paired-ttest')
stat=statPlot('talResults/Coh/cohLRv2post_D','talResults/Coh/cohLRv2pre_D',[freq freq],[0 1],'paired-ttest')
stat=statPlot('talResults/Coh/cohLRv1post_CQ','talResults/Coh/cohLRv1pre_CQ',[freq freq],[0 1],'paired-ttest')
stat=statPlot('talResults/Coh/cohLRv2post_CQ','talResults/Coh/cohLRv2pre_CQ',[freq freq],[0 1],'paired-ttest')
stat=statPlot('talResults/Coh/cohLRv1post_CV','talResults/Coh/cohLRv1pre_CV',[freq freq],[0 1],'paired-ttest')
stat=statPlot('talResults/Coh/cohLRv2post_CV','talResults/Coh/cohLRv2pre_CV',[freq freq],[0 1],'paired-ttest')

stat=statPlot('talResults/Coh/cohLRv2pre_D','talResults/Coh/cohLRv1pre_D',[freq freq],[0 1],'paired-ttest')
stat=statPlot('talResults/Coh/cohLRv2post_D','talResults/Coh/cohLRv1post_D',[freq freq],[0 1],'paired-ttest')
stat=statPlot('talResults/Coh/cohLRv2pre_CQ','talResults/Coh/cohLRv1pre_CQ',[freq freq],[0 1],'paired-ttest')
stat=statPlot('talResults/Coh/cohLRv2post_CQ','talResults/Coh/cohLRv1post_CQ',[freq freq],[0 1],'paired-ttest')
stat=statPlot('talResults/Coh/cohLRv2pre_CV','talResults/Coh/cohLRv1pre_CV',[freq freq],[0 1],'paired-ttest')
stat=statPlot('talResults/Coh/cohLRv2post_CV','talResults/Coh/cohLRv1post_CV',[freq freq],[0 1],'paired-ttest')

[~,figure1]=statPlot('talResults/oneBackCoh/NW/cohLRv2pre_D','talResults/oneBackCoh/NW/cohLRv1pre_D',[freq freq],[0 1],'paired-ttest')
saveas(figure1,'~/Desktop/D2_1pre.tif')
[~,figure1]=statPlot('talResults/oneBackCoh/NW/cohLRv2pre_CQ','talResults/oneBackCoh/NW/cohLRv1pre_CQ',[freq freq],[0 1],'paired-ttest')
saveas(figure1,'~/Desktop/CQ2_1pre.tif')
[~,figure1]=statPlot('talResults/oneBackCoh/NW/cohLRv2pre_CV','talResults/oneBackCoh/NW/cohLRv1pre_CV',[freq freq],[0 1],'paired-ttest')
saveas(figure1,'~/Desktop/CV2_1pre.tif')
[~,figure1]=statPlot('talResults/oneBackCoh/W/cohLRv2pre_D','talResults/oneBackCoh/W/cohLRv1pre_D',[freq freq],[0 1],'paired-ttest')
saveas(figure1,'~/Desktop/D2_1pre.tif')
[~,figure1]=statPlot('talResults/oneBackCoh/W/cohLRv2pre_CQ','talResults/oneBackCoh/W/cohLRv1pre_CQ',[freq freq],[0 1],'paired-ttest')
saveas(figure1,'~/Desktop/CQ2_1pre.tif')
[~,figure1]=statPlot('talResults/oneBackCoh/W/cohLRv2pre_CV','talResults/oneBackCoh/W/cohLRv1pre_CV',[freq freq],[0 1],'paired-ttest')
saveas(figure1,'~/Desktop/CV2_1pre.tif')

[~,figure1]=statPlot('talResults/timeProdCoh/cohLRv2pre_D','talResults/timeProdCoh/cohLRv1pre_D',[freq freq],[0 1],'paired-ttest')
saveas(figure1,'~/Desktop/D2_1pre.tif')
[~,figure1]=statPlot('talResults/timeProdCoh/cohLRv2pre_CQ','talResults/timeProdCoh/cohLRv1pre_CQ',[freq freq],[0 1],'paired-ttest')
saveas(figure1,'~/Desktop/CQ2_1pre.tif')
[~,figure1]=statPlot('talResults/timeProdCoh/cohLRv2pre_CV','talResults/timeProdCoh/cohLRv1pre_CV',[freq freq],[0 1],'paired-ttest')
saveas(figure1,'~/Desktop/CV2_1pre.tif')
