stat=statPlot('cohLRv1pre_DM','cohLRv1pre_CM',[4 4],[],'ttest2')
stat=statPlot('cohLRv1post_DM','cohLRv1post_CM',[4 4],[],'ttest2')
stat=statPlot('cohLRv2post_DM','cohLRv2post_CM',[4 4],[],'ttest2')
stat=statPlot('cohLRv2pre_DM','cohLRv2pre_CM',[4 4],[],'ttest2')
stat=statPlot('cohLRv1pre_DM','cohLRv1pre_CM',[10 10],[],'ttest2')
stat=statPlot('cohLRv1post_DM','cohLRv1post_CM',[10 10],[],'ttest2')
stat=statPlot('cohLRv2post_DM','cohLRv2post_CM',[10 10],[],'ttest2')
stat=statPlot('cohLRv2pre_DM','cohLRv2pre_CM',[10 10],[],'ttest2')

stat=statPlot('cohLRv1post_DM','cohLRv1pre_DM',[10 10],[],'paired-ttest')
stat=statPlot('cohLRv2post_DM','cohLRv2pre_DM',[10 10],[],'paired-ttest')
stat=statPlot('cohLRv1post_CM','cohLRv1pre_CM',[10 10],[],'paired-ttest')
stat=statPlot('cohLRv2post_CM','cohLRv2pre_CM',[10 10],[],'paired-ttest')
stat=statPlot('cohLRv1post_DM','cohLRv1pre_DM',[4 4],[],'paired-ttest')
stat=statPlot('cohLRv2post_DM','cohLRv2pre_DM',[4 4],[],'paired-ttest')
stat=statPlot('cohLRv1post_CM','cohLRv1pre_CM',[4 4],[],'paired-ttest')
stat=statPlot('cohLRv2post_CM','cohLRv2pre_CM',[4 4],[],'paired-ttest')

stat=statPlot('cohLRv2pre_DM','cohLRv1pre_DM',[10 10],[],'paired-ttest')
stat=statPlot('cohLRv2post_DM','cohLRv1post_DM',[10 10],[],'paired-ttest')
stat=statPlot('cohLRv2pre_CM','cohLRv1pre_CM',[10 10],[],'paired-ttest')
stat=statPlot('cohLRv2post_CM','cohLRv1post_CM',[10 10],[],'paired-ttest')
stat=statPlot('cohLRv2pre_DM','cohLRv1pre_DM',[4 4],[],'paired-ttest')
stat=statPlot('cohLRv2post_DM','cohLRv1post_DM',[4 4],[],'paired-ttest')
stat=statPlot('cohLRv2pre_CM','cohLRv1pre_CM',[4 4],[],'paired-ttest')
stat=statPlot('cohLRv2post_CM','cohLRv1post_CM',[4 4],[],'paired-ttest')
